#!/usr/bin/env bash
# PS5 RetroArch - build the WebUI daemon, a payload the title starts through the
# console's ELF loader (daemon/webui_daemon.cpp, src/webui_link.h): the WebUI's server
# and updater, as eboot.bin carries them, with a main of its own. Prints the ELF.
# Its libraries are eboot.bin's (tools/build-webui-http.sh, tools/build-webui-update.sh).
set -euo pipefail
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
sdk="$root/.deps/native/ps5-payload-sdk"
export PS5_PAYLOAD_SDK="$sdk" PS5_CLANG=${PS5_CLANG:-clang}
build="$root/build/webui-daemon"
mkdir -p "$build"
http=$(bash "$root/tools/build-webui-http.sh" ps5)
update=$(bash "$root/tools/build-webui-update.sh" ps5)
# HTTP and HTTPS through libcurl over mbedTLS 3.6 (tools/build-curl.sh): Sony's SSL
# failed every handshake from the payload (src/scraper_http.h). Its headers come first,
# so the updater's SHA-256 is mbedTLS 3.6's too: RetroArch's 2.x one (in libupdate.a)
# has the same names over other structures, and is left out below.
bash "$root/tools/build-curl.sh" >/dev/null
curl="$root/.deps/native/curl-ps5"
includes=(-I"$build" -I"$curl/include" -I"$root/src" -I"$root/.deps/webui/libmicrohttpd-1.0.10/src/include"
    -I"$root/.deps/native/zlib/zlib-1.3.2" -I"$root/.deps/native/zlib/zlib-1.3.2/contrib/minizip")
# ScreenScraper's developer account: read from the git-ignored .env
# (PS5_SCREENSCRAPER_DEVID, PS5_SCREENSCRAPER_DEVPASSWORD) into a header under build/
# (git-ignored), scrambled with a key drawn for this build so the binary holds no plain
# copy. Releases carry it too, scrambled as ES-DE ships its own (the owner's decision,
# 2026-10-07): it can be dug out of the binary, never read off the network (https only).
# PS5_SCREENSCRAPER_EXCLUDE=1 builds without it. tools/lint-shell.sh fails on any plain
# copy in a tracked or shipped file.
python3 - "$root/.env" "$build/screenscraper_dev.h" "${PS5_SCREENSCRAPER_EXCLUDE:-}" <<'PY_DEV'
import os, sys
env_path, out, exclude = sys.argv[1:4]
values = {}
if os.path.exists(env_path):
    for line in open(env_path):
        line = line.strip()
        if '=' in line and not line.startswith('#'):
            key, value = line.split('=', 1)
            values[key] = value.strip('"')
devid = os.environ.get('PS5_SCREENSCRAPER_DEVID') or values.get('PS5_SCREENSCRAPER_DEVID', '')
password = os.environ.get('PS5_SCREENSCRAPER_DEVPASSWORD') or values.get('PS5_SCREENSCRAPER_DEVPASSWORD', '')
text = '/* Generated by tools/build-webui-daemon.sh; never commit it. */\n'
if exclude == '1' or not devid or not password:
    text += '#define PS5_SS_DEV 0\n'
else:
    key = os.urandom(32)
    def bytes_of(s):
        return ','.join(str(b ^ key[i % len(key)]) for i, b in enumerate(s.encode()))
    text += ('#define PS5_SS_DEV 1\n'
             f'static const unsigned char ps5_ss_key[] = {{{",".join(map(str, key))}}};\n'
             f'static const unsigned char ps5_ss_devid[] = {{{bytes_of(devid)}}};\n'
             f'static const unsigned char ps5_ss_devpassword[] = {{{bytes_of(password)}}};\n')
fd = os.open(out, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
with os.fdopen(fd, 'w') as file:
    file.write(text)
print('ScreenScraper developer account: ' + ('none (excluded)' if exclude == '1' else 'built in (scrambled)' if 'DEV 1' in text else 'none (.env has none)'), file=sys.stderr)
PY_DEV
objects=()
# The game servers' setup (src/remote/servers.h), with the backends it signs in through.
remote_sources=(src/remote/servers src/remote/backends src/remote/files src/remote/save_config
    src/remote/romm/romm_client src/remote/romm/romm_source src/remote/romm/romm_firmware
    src/remote/romm/romm_saves src/remote/romm/romm_setup)
for source in daemon/webui_daemon src/webui_ps5 src/webui_transfer src/webui_update src/scraper src/scraper_http \
    "${remote_sources[@]}"; do
    "$sdk/bin/prospero-clang++" -std=c++17 -O2 -Wall -Werror -DPS5_SCRAPER_CURL "${includes[@]}" \
        -c "$root/$source.cpp" -o "$build/${source##*/}.o"
    objects+=("$build/${source##*/}.o")
done
# The shared game library (src/ps5_library.c), which the scraper reads, as every frontend.
"$sdk/bin/prospero-clang" -std=c11 -O2 -Wall -Werror -c "$root/src/ps5_library.c" -o "$build/ps5_library.o"
objects+=("$build/ps5_library.o")
# The daemon's own files are 0777, as the title's (daemon/webui_daemon.cpp).
# The updater's zip reading only, from libupdate.a (its SHA-256 is mbedTLS 3.6's).
update_build=$(dirname "$update")
"$sdk/bin/prospero-clang++" -o "$build/ps5-retroarch-webui.elf" "${objects[@]}" "$http" \
    "$update_build/ioapi.o" "$update_build/unzip.o" \
    "$curl/lib/libcurl.a" "$curl/lib/libmbedtls.a" "$curl/lib/libmbedx509.a" "$curl/lib/libmbedcrypto.a" \
    "$root/.deps/native/zlib/root/usr/lib/libz.a" \
    -Wl,--wrap=mkdir -Wl,--wrap=open -Wl,--wrap=fopen -lSceNet
printf '%s\n' "$build/ps5-retroarch-webui.elf"
